const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const safeLink=value=>{try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)&&!url.username&&!url.password?url.href:'';}catch{return '';}};

/** An inert standalone document: no scripts, images, tracking or remote requests. */
export function buildPublishableCollectionHTML(cards,{title='梦藏收藏集',description='',includeNotes=false}={}) {
  if(!Array.isArray(cards)||!cards.length||cards.length>2000)throw Error('请选择 1 至 2000 张卡片生成合集页面。');
  let bytes=0;
  const entries=cards.map((card,index)=>{
    const href=safeLink(card.sourceUrl),body=String(card.body||''),note=includeNotes?String(card.caption||''):'';
    const entry=`<article id="card-${index+1}"><span class="index">${String(index+1).padStart(2,'0')}</span><h2>${escape(card.title||'未命名卡片')}</h2>${body?`<div class="body">${escape(body)}</div>`:''}${card.ocrText?`<details><summary>图片识别文字</summary><div class="body">${escape(card.ocrText)}</div></details>`:''}${note?`<aside><h3>我的备注</h3><div class="body">${escape(note)}</div></aside>`:''}<footer>${card.sourceTitle?`<span>${escape(card.sourceTitle)}</span>`:''}${card.author?`<span>${escape(card.author)}</span>`:''}${card.page?`<span>第 ${escape(card.page)} 页</span>`:''}${card.sourceLocation?`<span>${escape(card.sourceLocation)}</span>`:''}${href?`<a href="${escape(href)}" target="_blank" rel="noopener noreferrer">查看原始来源 ↗</a>`:''}</footer>${card.attachment?'<p class="attachment">此卡片包含本机附件，原文件未包含在此合集页面中。</p>':''}</article>`;
    bytes+=new TextEncoder().encode(entry).length;if(bytes>16*1024*1024)throw Error('合集页面超过 16 MiB，请分批导出。');return entry;
  }).join('\n');
  const html=`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>${escape(title)}</title><style>
:root{color-scheme:dark;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif;background:#0d1117;color:#c9d1d9}*{box-sizing:border-box}body{margin:0;padding:64px 24px 36px}main,header.page,footer.page{max-width:1000px;margin:auto}.eyebrow{font-size:13px;color:#8b949e;letter-spacing:.08em}h1{font-size:clamp(28px,5vw,48px);font-weight:500;line-height:1.2;margin:18px 0}header.page{margin-bottom:42px}header.page p{white-space:pre-wrap;line-height:1.8;color:#8b949e}main{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px;align-items:start}article{min-width:0;background:#21262d;border:1px solid #30363d;border-radius:18px;padding:28px}.index{font-size:12px;color:#8b949e}h2{font-size:21px;line-height:1.45;font-weight:500;overflow-wrap:anywhere;margin:16px 0}h3{font-size:13px;font-weight:500;margin:0 0 8px;color:#8b949e}.body{white-space:pre-wrap;overflow-wrap:anywhere;font-size:15px;line-height:1.9}article footer{display:flex;flex-wrap:wrap;gap:8px 14px;margin-top:22px;font-size:12px;line-height:1.7;color:#8b949e}a{color:#55b6ff}aside{border-left:2px solid #55b6ff;padding:10px 0 10px 16px;margin-top:20px}details{margin-top:20px}summary{cursor:pointer;color:#8b949e;font-size:13px;margin-bottom:10px}.attachment,footer.page{color:#8b949e;font-size:12px;line-height:1.7}.attachment{margin:18px 0 0}footer.page{margin-top:36px}@media(max-width:650px){body{padding:36px 18px}main{grid-template-columns:1fr}article{padding:23px}}@media print{:root{color-scheme:light;background:white;color:#222}body{padding:0}main{display:block}article{background:white;border-color:#bbb;break-inside:avoid;margin-bottom:18px}a{color:#174b7a}}
</style></head><body><header class="page"><div class="eyebrow">梦藏 · 收藏集</div><h1>${escape(title)}</h1>${description?`<p>${escape(description)}</p>`:''}<p>${cards.length} 张卡片</p></header><main>${entries}</main><footer class="page">由梦藏导出的独立阅读页面。素材保留原文；页面不含原始附件，不连接资料库，不执行 AI 请求。公开发布前请自行确认素材的分享范围。</footer></body></html>`;
  if(new TextEncoder().encode(html).length>16*1024*1024)throw Error('合集页面超过 16 MiB，请分批导出。');
  return html;
}
