import WorkspaceSearch from './WorkspaceSearch.jsx';
import React,{useEffect,useRef,useState} from 'react';
import {IconBulb,IconPhoto,IconBook2,IconFolder,IconSettings,IconX,IconCheck,IconPlus,IconArrowUpRight,IconLeaf,IconAlertCircle,IconCalendarEvent} from '@tabler/icons-react';
import Inspiration from './Inspiration.jsx';
import {MaterialsView,BooksView} from './Collections.jsx';
import ScheduleView from './ScheduleView.jsx';
import {readPreviewSchedules,createSchedulePreview,previewScheduleIdentity} from './schedulePreview.js';
import Reader from './Reader.jsx';
import SublimeWorkspace from './sublime/SublimeWorkspace.jsx';
import {discoverySeeds,makeDiscoveryPreview,readDiscoveryItems,discoveryPreviewIdentity} from './discoveryPreview.js';
import {inspirationSeeds,materialSeeds,bookSeeds} from './data.js';
const STORAGE='mengcang-desktop-preview-v1';
function load(){try{const v=JSON.parse(localStorage.getItem(STORAGE));return v?.version===1?v:null}catch{return null}}
function ModalShell({children,onClose,label}){const ref=useRef(null);useEffect(()=>{const d=ref.current;d.showModal();return()=>d.close()},[]);return <dialog ref={ref} className="root-dialog" aria-label={label} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===e.currentTarget)onClose()}}>{children}</dialog>}
export function App(){
 const initial=useRef(load());const [entries,setEntries]=useState(initial.current?.entries||inspirationSeeds),[materials,setMaterials]=useState(initial.current?.materials||discoverySeeds),[books,setBooks]=useState(initial.current?.books||bookSeeds),[notes,setNotes]=useState(initial.current?.notes||[]),[projects,setProjects]=useState(initial.current?.projects||[]);
 const [schedules,setSchedules]=useState(readPreviewSchedules);const scheduleApi=useRef(null);if(!scheduleApi.current)scheduleApi.current=createSchedulePreview(setSchedules);
 const materialRef=useRef(materials);materialRef.current=materials;
 const discoveryApi=useRef(null);if(!discoveryApi.current)discoveryApi.current=makeDiscoveryPreview(()=>materialRef.current,next=>{materialRef.current=next;setMaterials(next);});
 const [discoveryOpen,setDiscoveryOpen]=useState(true);
 const urlView=new URLSearchParams(location.search).get('view');
 const [view,setView]=useState(['inspiration','materials','books','reader','projects','schedule'].includes(urlView)?urlView:initial.current?.view||'inspiration'),[activeBook,setActiveBook]=useState(initial.current?.activeBook||'b-tree'),[materialId,setMaterialId]=useState(null),[materialNavigation,setMaterialNavigation]=useState(0),[settings,setSettings]=useState(false),[toast,setToast]=useState(''),[reduced,setReduced]=useState(initial.current?.reduced??matchMedia('(prefers-reduced-motion: reduce)').matches),[saveError,setSaveError]=useState(''),[projectDraft,setProjectDraft]=useState(null);
 const toastTimer=useRef();const notify=message=>{setToast(message);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),3200)};
 const go=next=>{const proceed=()=>{setView(next);history.replaceState(null,'',`?view=${next}`)};const event=new CustomEvent('mengcang-before-leave',{cancelable:true,detail:{proceed}});if(window.dispatchEvent(event))proceed();};
 useEffect(()=>{try{localStorage.setItem(STORAGE,JSON.stringify({version:1,entries,materials,books,notes,projects,view,activeBook,reduced}));setSaveError('')}catch{setSaveError('本机预览保存失败，请保留当前页面并导出草稿。')}},[entries,materials,books,notes,projects,view,activeBook,reduced]);
 useEffect(()=>{const key=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();Array.from(document.querySelectorAll('.view-content .search-field input')).find(n=>n.getClientRects().length)?.focus()}if(e.key==='Escape'){setSettings(false);setProjectDraft(null)}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[]);
 function exportDraft(){let readerPreview=null;try{readerPreview=JSON.parse(localStorage.getItem('mengcang-reader-preview-v1')||'null')}catch{}const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,entries,materials,books,notes,projects,schedules,readerPreview},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='梦藏-交互预览草稿.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('预览草稿已导出')}
 const book=books.find(b=>b.id===activeBook)||books[0];
 const [projectQuery,setProjectQuery]=useState('');
 const visibleProjects=projects.filter(project=>[project.title,project.goal,project.sourceTitle].filter(Boolean).join(' ').toLocaleLowerCase().includes(projectQuery.trim().toLocaleLowerCase()));
 const nav=[{id:'inspiration',name:'灵感',Icon:IconBulb},{id:'materials',name:'素材',Icon:IconPhoto},{id:'books',name:'藏书',Icon:IconBook2},{id:'projects',name:'项目',Icon:IconFolder},{id:'schedule',name:'日程',Icon:IconCalendarEvent}];
 function saveProject(e){e.preventDefault();const f=new FormData(e.currentTarget);const p={id:projectDraft.id||crypto.randomUUID(),title:f.get('title').trim(),goal:f.get('goal').trim(),sourceId:projectDraft.sourceId,sourceTitle:projectDraft.sourceTitle};if(!p.title)return;setProjects(all=>projectDraft.id?all.map(x=>x.id===p.id?p:x):[...all,p]);setProjectDraft(null);go('projects');notify('项目入口已保存在此预览中')}
 return <div className={`desktop-app ${reduced?'reduce-motion':''} ${view==='materials'&&discoveryOpen?'is-sublime-discovery':''}`}>
 <aside className="app-nav" inert={view==='materials'&&discoveryOpen}><div className="window-dots" aria-hidden="true"><i/><i/><i/></div><button className="brand" onClick={()=>go('inspiration')} aria-label="梦藏首页"><IconLeaf size={25} stroke={1.4}/><span>梦藏</span></button><nav>{nav.map(({id,name,Icon})=><button key={id} className={`nav-link ${(view===id||(view==='reader'&&id==='books'))?'active':''}`} aria-current={(view===id||(view==='reader'&&id==='books'))?'page':undefined} onClick={()=>go(id)}><Icon size={20} stroke={1.45}/><span>{name}</span></button>)}</nav><div className="nav-bottom"><span className="preview-indicator" title="设计交互预览，未连接真实仓库"><i/>交互预览</span><button className="nav-link" onClick={()=>setSettings(true)}><IconSettings size={20} stroke={1.4}/><span>设置</span></button></div></aside>
 <div className="view-content">
 <section className="view-panel" hidden={view!=='inspiration'}><Inspiration entries={entries} setEntries={setEntries} materials={materials} notify={notify} onMaterial={id=>{setMaterialId(id||'__all');setMaterialNavigation(n=>n+1);go('materials')}} onCreateProject={item=>setProjectDraft({title:item.suggestedTitle||item.title,sourceId:item.id,sourceTitle:item.title})}/></section>
 <section className="view-panel" hidden={view!=='materials'}><div className="discovery-entry-bar" hidden={discoveryOpen}><button className="text-btn" onClick={()=>setDiscoveryOpen(!discoveryOpen)}>{discoveryOpen?'查看原素材网格':'打开素材发现'}</button></div>{discoveryOpen&&view==='materials'?<SublimeWorkspace items={materials} api={discoveryApi.current} identity={discoveryPreviewIdentity} demo onExit={()=>setDiscoveryOpen(false)}/>:<MaterialsView materials={materials} setMaterials={setMaterials} initialMaterialId={materialId} navigationKey={materialNavigation} notify={notify} onOpenSettings={()=>setSettings(true)}/>}</section>
 <section className="view-panel" hidden={view!=='books'}><BooksView books={books} setBooks={setBooks} onRead={b=>{setActiveBook(b.id);go('reader')}} notify={notify}/></section>

 {view==='reader'&&book&&<Reader book={book} page={book.page||1} onPage={page=>setBooks(all=>all.map(b=>b.id===book.id?{...b,page}:b))} onExit={()=>go('books')} notes={notes} setNotes={setNotes} notify={notify} reducedMotion={reduced}/>}
 <section className="view-panel" hidden={!['projects','schedule'].includes(view)}><ScheduleView items={schedules} projects={projects} sources={[]} api={scheduleApi.current} identity={previewScheduleIdentity} connected enabled workEnabled mode={view==='projects'?'projects':'schedule'} activeView={['projects','schedule'].includes(view)} projectsContent={<div className="projects-view"><header className="page-heading workspace-search-header"><WorkspaceSearch label="搜索项目" placeholder="搜索项目名称或目标…" value={projectQuery} onChange={setProjectQuery}/><button className="btn btn-primary" onClick={()=>setProjectDraft({title:''})}><IconPlus size={17}/>建立项目</button></header><div className="projects-main">{projects.length?<><div className="projects-grid">{visibleProjects.map(p=><article className="project-card" key={p.id}><IconFolder size={27} stroke={1.2}/><h2>{p.title}</h2><p>{p.goal||'还没确定目标，可以慢慢探索。'}</p>{p.sourceTitle&&<span className="project-source">来自灵感 · {p.sourceTitle}</span>}<button className="text-btn" onClick={()=>setProjectDraft(p)}>编辑项目入口<IconArrowUpRight size={15}/></button></article>)}</div>{!visibleProjects.length && <p className="desktop-empty-hint" role="status">没有匹配的项目，试试其他关键词。</p>}</>:<div className="project-empty"><IconFolder size={44} stroke={1}/><h2>从一个想法开始</h2><p>当方向逐渐清晰，就为它建立一个项目。<br/>也可以从灵感详情中直接带入。</p><button className="btn" onClick={()=>go('inspiration')}>回到灵感<IconArrowUpRight size={16}/></button></div>}</div></div>} onSaved={()=>setSchedules(readPreviewSchedules())} onPreview={()=>{}} notify={notify} reducedMotion={reduced || !['projects','schedule'].includes(view)}/></section>
 </div>
 {saveError&&<div role="alert" className="save-error"><IconAlertCircle size={16}/>{saveError}<button onClick={exportDraft}>导出草稿</button></div>}
 {toast&&<div className="toast" role="status"><IconCheck size={16}/>{toast}</div>}
 {settings&&<ModalShell label="设置" onClose={()=>setSettings(false)}><section className="modal settings-modal"><div className="modal-heading"><h2 id="settings-title">设置</h2><button autoFocus className="icon-btn" aria-label="关闭设置" onClick={()=>setSettings(false)}><IconX size={20}/></button></div><div className="settings-section"><h3>当前预览</h3><p>这是梦藏桌面的交互设计预览。内容为示例，编辑只保存在当前浏览器，可以刷新后继续查看。</p><button className="btn" onClick={exportDraft}>导出预览草稿</button></div><div className="settings-section"><h3>Obsidian 连接 <span className="status-chip">未连接</span></h3><p>真实笔记保存、备忘录同步和网页快照将在下一阶段接入。本次预览不会修改 Personal AI OS 仓库。</p></div><div className="setting-toggle"><div><h3>减少动态效果</h3><p>关闭页面淡入与悬停位移。</p></div><button className={`toggle ${reduced?'on':''}`} role="switch" aria-label="减少动态效果" aria-checked={reduced} onClick={()=>setReduced(!reduced)}><span/></button></div><div className="settings-section fine-print">示例图片与书封来自你提供的设计图；阅读页为可交互排版示例，尚未接入 PDF 文件。<br/>搜索快捷键：⌘ K</div></section></ModalShell>}
 {projectDraft&&<ModalShell label="项目编辑" onClose={()=>setProjectDraft(null)}><form className="modal" onSubmit={saveProject}><div className="modal-heading"><h2 id="project-title">{projectDraft.id?'编辑项目':'建立项目'}</h2><button className="icon-btn" type="button" aria-label="关闭项目编辑" onClick={()=>setProjectDraft(null)}><IconX size={20}/></button></div><label>项目名称<input autoFocus required name="title" defaultValue={projectDraft.title}/></label><label>想做什么 <span className="muted">· 可以留空</span><textarea name="goal" rows={4} defaultValue={projectDraft.goal||''} placeholder="此刻想清楚的部分就好…"/></label>{projectDraft.sourceTitle&&<p className="muted">来源灵感：{projectDraft.sourceTitle}</p>}<div className="modal-actions"><button className="btn" type="button" onClick={()=>setProjectDraft(null)}>取消</button><button className="btn btn-primary" type="submit">{projectDraft.id?'保存修改':'建立项目入口'}</button></div></form></ModalShell>}
 </div>
}
