import WorkspaceSearch from './WorkspaceSearch.jsx';
import React, { useEffect, useMemo, useRef, useState } from 'react';
import { IconPlus, IconSearch, IconX, IconPencil, IconArrowUp, IconCheck, IconChevronLeft, IconChevronRight, IconBook2, IconFolder, IconArrowBackUp, IconSparkles, IconFileText } from '@tabler/icons-react';
import { Art, EmptyState } from './common';
import { searchText } from './desktopModel.js';
import { useWorkspaceNavigation } from './useWorkspaceNavigation.js';
import './inspiration.css';

const uid = () => `i-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const tintFor = id => ['mint','blue','sage','sand'][Array.from(id).reduce((n,c) => n+c.charCodeAt(0),0)%4];
const shortDate = date => String(date || '').slice(0,10).replaceAll('-','/');
const roleName = role => role === 'reference' ? '参考素材' : '起点灵感';

function InspirationEditor({entry,onClose,onSave}) {
  const ref = useRef(null);
  const [form,setForm] = useState(entry ? {...entry} : {title:'',summary:'',body:'',role:'inspiration',category:'影像与叙事',art:''});
  useEffect(() => {ref.current?.showModal();},[]);
  const change = (key,value) => setForm(prev => ({...prev,[key]:value}));
  const submit = e => {e.preventDefault();if(!form.title.trim())return; const id = entry?.id || uid();onSave({...form,id,title:form.title.trim(),summary:form.summary.trim() || form.body.trim().slice(0,65),body:form.body.trim(),date:entry?.date || new Date().toLocaleDateString('sv-SE'),tint:entry?.tint || tintFor(id),related:entry?.related || [],explorations:entry?.explorations || [],relations:entry?.relations || [],confirmed:entry?.confirmed || false});};
  return <dialog ref={ref} className="inspiration-editor" onCancel={e => {e.preventDefault();onClose();}} onClick={e => {if(e.target === e.currentTarget)onClose();}}><form onSubmit={submit}><div className="inspiration-editor-heading"><h2>{entry ? '编辑灵感' : '记下一束灵感'}</h2><button type="button" className="icon-btn" aria-label="关闭灵感编辑" onClick={onClose}><IconX size={19}/></button></div><p>不必完整，先把闪过的念头留下来。</p><label>标题<input autoFocus required placeholder="此刻，你想到了什么？" value={form.title} onChange={e => change('title',e.target.value)}/></label><div className="inspiration-editor-row"><label>它的作用<select value={form.role} onChange={e => change('role',e.target.value)}><option value="inspiration">起点灵感</option><option value="reference">参考素材</option></select></label><label>分类<select value={form.category} onChange={e => change('category',e.target.value)}><option>影像与叙事</option><option>空间与体验</option><option>文字与思考</option><option>日常与生活</option></select></label></div><label>一句话描述<input placeholder="用一句话留住它的感觉" value={form.summary} onChange={e => change('summary',e.target.value)}/></label><label>灵感内容<textarea rows={7} placeholder="慢慢写下它的样子…" value={form.body} onChange={e => change('body',e.target.value)}/></label><label>搭配一张示例图片<select value={form.art || ''} onChange={e => change('art',e.target.value)}><option value="">暂不添加</option><option value="mist">山间晨雾</option><option value="coast">海岸与风</option><option value="leafShadow">午后叶影</option><option value="plant">窗边绿意</option><option value="lake">湖畔时光</option></select></label><div className="inspiration-editor-foot"><span>仅保存在本机浏览器</span><button type="button" className="btn" onClick={onClose}>取消</button><button type="submit" className="btn btn-primary"><IconCheck size={15}/>保存灵感</button></div></form></dialog>;
}

export default function Inspiration({entries = [],setEntries,materials = [],onMaterial,onCreateProject,notify,desktop}) {
  const [selectedId,setSelectedId] = useState(entries[0]?.id);
  const [query,setQuery] = useState('');
  const [role,setRole] = useState('all');
  const [category,setCategory] = useState('all');
  const [editor,setEditor] = useState(null);
  const [mobileDetail,setMobileDetail] = useState(false);
  const visible = useMemo(() => entries.filter(e => (role === 'all' || e.role === role) && (category === 'all' || e.category === category) && searchText(e).includes(query.toLocaleLowerCase())),[entries,role,category,query]);
  useEffect(() => {if(!visible.some(e => e.id === selectedId)) setSelectedId(visible[0]?.id);},[visible,selectedId]);
  const item = visible.find(e => e.id === selectedId) || visible[0];
  const managedNavigation = useWorkspaceNavigation(desktop, 'inspiration', {
    capture: () => ({query, role, category, selectedId:item?.id || null, mobileDetail}),
    restore: state => {
      setQuery(state?.query ?? '');setRole(state?.role ?? 'all');setCategory(state?.category ?? 'all');
      setSelectedId(state?.selectedId ?? undefined);setMobileDetail(Boolean(state?.mobileDetail));
    },
    open: path => {
      if (!path) return false;
      const target = entries.find(entry => entry.path === path);
      if (!target) return false;
      if (!searchText(target).includes(query.toLocaleLowerCase())) setQuery('');
      if (role !== 'all' && target.role !== role) setRole('all');
      if (category !== 'all' && target.category !== category) setCategory('all');
      setSelectedId(target.id);setMobileDetail(true);return true;
    },
  });
  const draft = item?.exploreDraft || '';
  useEffect(() => {if(!managedNavigation && desktop?.selectedPath){const target=entries.find(e=>e.path===desktop.selectedPath);if(target){setSelectedId(target.id);setQuery('');setRole('all');setCategory('all');setMobileDetail(true);}}},[managedNavigation,desktop?.selectedPath,desktop?.navigationKey]);
  const select = id => {if(id !== item?.id) desktop?.onBeforeSelect?.();setSelectedId(id);setMobileDetail(true);};
  const categories = [...new Set(entries.map(e => e.category).filter(Boolean))];
  const related = item ? materials.filter(m => (item.related || []).includes(m.id)) : [];
  const patch = changes => setEntries(prev => prev.map(e => e.id === item.id ? {...e,...changes} : e));
  const saveExplore = () => {if(!draft.trim())return;patch({explorations:[...(item.explorations || []),{id:uid(),text:draft.trim(),date:new Date().toISOString()}],exploreDraft:''});notify?.('探索已保存在此预览中');};
  const saveEntry = next => {setEntries(prev => prev.some(e => e.id === next.id) ? prev.map(e => e.id === next.id ? next : e) : [next,...prev]);setSelectedId(next.id);setEditor(null);setQuery('');setRole('all');setCategory('all');setMobileDetail(true);notify?.('灵感已保存在本机浏览器');};
  const candidates = item ? [{id:'book-tree',kind:'book',title:'《山与树的对话》',label:'书籍',reason:'同样关注自然中的日常，或许能延伸这段思考。'},{id:`project-${item.id}`,kind:'project',title:item.category === '空间与体验' ? '日常的栖息地' : '慢下来的日常',label:'项目',reason:`从「${item.title}」出发，收集相关的文字与画面。`}] : [];
  const relationStatus = id => (item?.relations || []).find(r => (typeof r === 'string' ? r : r.id) === id)?.status || 'pending';
  const setRelation = (candidate,status) => {patch({relations:[...(item.relations || []).filter(r => (typeof r === 'string' ? r : r.id) !== candidate.id),...(status === 'pending' ? [] : [{id:candidate.id,title:candidate.title,kind:candidate.kind,status}])]});notify?.(status === 'confirmed' ? '已确认这条本地关联' : status === 'skipped' ? '已跳过这条建议，可随时撤回' : '关联已撤回');};
  return <div className={`inspiration-view ${mobileDetail ? 'inspiration-show-detail' : ''}`}>
    <header className="inspiration-page-header workspace-search-header"><WorkspaceSearch label="搜索灵感" placeholder="搜索灵感…" value={query} onChange={setQuery}/><span>{!desktop && <button className="btn btn-primary" onClick={() => setEditor({mode:'new'})}><IconPlus size={15}/>新建灵感</button>}</span></header>
    <div className="inspiration-workspace"><aside className="inspiration-list"><div className="inspiration-list-filters"><div className="inspiration-role-filter">{[['all','全部'],['inspiration','起点灵感'],['reference','参考素材']].map(([key,label]) => <button className={role === key ? 'is-active' : ''} key={key} onClick={() => setRole(key)}>{label}</button>)}</div><select aria-label="灵感分类" value={category} onChange={e => setCategory(e.target.value)}><option value="all">所有分类</option>{categories.map(c => <option key={c} value={c}>{c}</option>)}</select></div><div className="inspiration-cards">{visible.map(entry => <button key={entry.id} className={`inspiration-card inspiration-tint-${entry.tint || tintFor(entry.id)} ${item?.id === entry.id ? 'is-selected' : ''}`} onClick={() => select(entry.id)} aria-pressed={item?.id === entry.id}><span className="inspiration-card-copy"><strong>{entry.title}{entry.confirmed && <IconCheck size={12}/>}</strong><span className="inspiration-card-summary">{entry.summary}</span><span className="inspiration-card-date">{entry.dateLabel || shortDate(entry.date)}<span>{roleName(entry.role)}</span></span></span>{(entry.art || entry.assetUrl) && <Art real={entry.real} src={entry.assetUrl} name={entry.art} alt="" className="inspiration-card-art"/>}</button>)}{!visible.length && <EmptyState title="还没有找到这束灵感" description="试试其他关键词，或记下一个新念头。"/>}</div><div className="inspiration-list-footer">{visible.length} 条灵感<span>让想法慢慢发生</span></div></aside>
    {item ? desktop ? <><main className="inspiration-document"><div className="inspiration-mobile-back"><button className="text-btn" onClick={() => setMobileDetail(false)}><IconChevronLeft size={17}/>全部灵感</button></div>{desktop.renderDetail(item)}</main><aside className="inspiration-related">{desktop.renderRelated(item)}</aside></> : <><main className="inspiration-document"><div className="inspiration-mobile-back"><button className="text-btn" onClick={() => setMobileDetail(false)}><IconChevronLeft size={17}/>全部灵感</button></div><div className="inspiration-document-heading"><div><h2>{item.title}</h2><div className="inspiration-document-meta"><span>{shortDate(item.date)}</span><span>{item.category}</span></div></div><button className="icon-btn" aria-label="编辑当前灵感" title="编辑灵感" onClick={() => setEditor({mode:'edit',entry:item})}><IconPencil size={17}/></button></div><div className="inspiration-body-copy">{(item.body || item.summary).split('\n\n').filter(Boolean).map((text,index) => <p key={index}>{text}</p>)}</div>{item.art && <Art name={item.art} alt={item.title} className="inspiration-hero"/>}
      {(item.explorations || []).length > 0 && <section className="inspiration-history"><h3>沿着这个念头</h3>{item.explorations.map(explore => <article key={explore.id}><span>{shortDate(explore.date)}</span><p>{explore.text}</p></article>)}</section>}
      <section className="inspiration-explore"><label htmlFor="inspiration-explore-input">继续探索这个灵感…</label><textarea id="inspiration-explore-input" value={draft} onChange={e => patch({exploreDraft:e.target.value})} placeholder="它还让你想到了什么？" rows={3}/><div className="inspiration-explore-bottom"><div className="inspiration-prompts">{['可以从什么角度展开？','想关联哪些内容？','突然想到其他方向？'].map(prompt => <button key={prompt} onClick={() => {patch({exploreDraft:`${draft}${draft ? '\n' : ''}${prompt}\n`});document.getElementById('inspiration-explore-input')?.focus();}}>{prompt}</button>)}</div><button className="inspiration-explore-save" aria-label="保存探索内容" title="保存探索" disabled={!draft.trim()} onClick={saveExplore}><IconArrowUp size={18}/></button></div></section>
      {!item.confirmed ? <div className="inspiration-organize"><div><IconCheck size={17}/><span><strong>等想法清晰一点，再整理它</strong><small>确认后标记为已整理，保留所有探索记录。</small></span></div><button className="text-btn" onClick={() => {patch({confirmed:true});notify?.('已在原型中标记为已整理');}}>确认整理</button></div> : <button className="text-btn" style={{fontSize:10,color:'#91a57c',marginTop:16}} onClick={() => {patch({confirmed:false});notify?.('已撤销整理标记');}}>撤销整理</button>}<button className="inspiration-project-cta text-btn" onClick={() => onCreateProject?.(item)}><IconFolder size={14}/>从这条灵感创建项目<IconChevronRight size={14}/></button><p className="inspiration-local-note">这里的内容和关联仅保存在本机浏览器，尚未写入知识库。</p>
    </main><aside className="inspiration-related"><div className="inspiration-related-heading"><h3>相关素材 <span>({related.length})</span></h3><button className="text-btn" onClick={() => onMaterial?.(null)}>查看更多</button></div><div className="inspiration-related-list">{related.map(material => <button className="inspiration-related-item" key={material.id} onClick={() => onMaterial?.(material.id)}>{material.art ? <Art name={material.art} alt=""/> : <span className="inspiration-related-text-icon"><IconFileText size={25} stroke={1.1}/></span>}<span><strong>{material.title}</strong><small>{material.type === 'image' ? '图片' : material.type === 'web' ? '网页' : '文字'} · {shortDate(material.date)}</small></span><IconChevronRight className="inspiration-related-arrow" size={13}/></button>)}</div><section className="inspiration-candidates"><h3>待确认的关联 <span>({candidates.filter(c => relationStatus(c.id) === 'pending').length})</span></h3><p className="inspiration-candidate-intro">一些可能的连接，等你来决定。</p>{candidates.map(candidate => {const status = relationStatus(candidate.id);return <article className={`inspiration-candidate inspiration-candidate-${status}`} key={candidate.id}><div className="inspiration-candidate-title">{candidate.kind === 'book' ? <IconBook2 size={21} stroke={1.35}/> : <IconFolder size={21} stroke={1.35}/>}<strong>{candidate.title}<small>{candidate.label}</small></strong></div><p>{candidate.reason}</p><div className="inspiration-candidate-actions">{status === 'pending' ? <><button className="text-btn" onClick={() => setRelation(candidate,'confirmed')}><IconCheck size={12}/>确认关联</button><button className="text-btn" onClick={() => setRelation(candidate,'skipped')}>跳过</button></> : <><span>{status === 'confirmed' ? '已确认' : '已跳过'}</span><button className="text-btn" onClick={() => setRelation(candidate,'pending')}><IconArrowBackUp size={12}/>撤回</button></>}</div>{candidate.kind === 'project' && status === 'confirmed' && <button className="inspiration-candidate-create text-btn" onClick={() => onCreateProject?.({...item,suggestedTitle:candidate.title})}>创建这个项目<IconChevronRight size={12}/></button>}</article>;})}</section><div className="inspiration-quiet-note"><IconSparkles size={17} stroke={1.25}/><p>想法之间的连接，<br/>有时比想法本身更有趣。</p></div></aside></> : <main className="inspiration-document"><EmptyState title="先留下一束灵感" description={desktop ? "当前筛选范围中没有灵感记录。" : "从一句话、一张画面，或一个偶然的念头开始。"}/></main>}
    </div>{editor && <InspirationEditor entry={editor.mode === 'edit' ? editor.entry : undefined} onClose={() => setEditor(null)} onSave={saveEntry}/>}
  </div>;
}
