'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {randomUUID}=require('node:crypto');
const {LocalVaultGateway}=require('../desktop/local-gateway.cjs');
const {splitNote,frontmatterOf,hash}=require('../src/desktop-connector/notes.js');
const {rejectAiRequest}=require('../desktop/ai-policy.cjs');
function harness(t){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'mengcang-standalone-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return {root,gateway:new LocalVaultGateway({vaultPath:root,cachePath:path.join(root,'cache.json')}),write(relative,body){const file=path.join(root,relative);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,body);return file;}};}
const request=extra=>({operationId:randomUUID(),title:'独立软件测试',body:' 原文\r\n第二行 café 🧪  ',caption:'本机笔记',tags:['test'],...extra});
const attachment={name:'pixel.png',type:'image/png',size:79,dataUrl:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAFklEQVR4nGL4z8DAAAQBAQAA//8DAAEHAQD6RQNLAAAAAElFTkSuQmCC'};
attachment.size=Buffer.from(attachment.dataUrl.split(',')[1],'base64').length;

test('standalone filesystem read needs no plugin/config/account and scans nested notes',async t=>{
 const h=harness(t);h.write('01_sources/cards/text/nested/source.md','---\ntype: material\ntitle: 真实格式\ncaption: 笔记\n---\n正文');h.write('01_sources/books/book.md','---\ntype: book\ntitle: 图书\n---\n原文');
 const before=hash(fs.readFileSync(path.join(h.root,'01_sources/cards/text/nested/source.md')));const result=await h.gateway.snapshot();
 assert.equal(h.gateway.status().connected,true);assert.equal(result.materials.length,1);assert.equal(result.books.length,1);assert.equal(result.errors.length,0);assert.equal(result.materials[0].title,'真实格式');assert.equal(hash(fs.readFileSync(path.join(h.root,'01_sources/cards/text/nested/source.md'))),before);assert.equal(fs.existsSync(path.join(h.root,'.obsidian')),false);
});
test('missing material directory leaves local workspace usable with capture disabled',async t=>{const h=harness(t);const g=new LocalVaultGateway({vaultPath:path.join(h.root,'missing'),cachePath:path.join(h.root,'cache')});assert.equal(g.status().connected,false);assert.equal(g.status().identity.id,'unpaired');assert.equal((await g.snapshot()).capabilities.capture,false);});
test('uses matching previous workspace identity without opening plugin credentials',t=>{const h=harness(t);h.write('cache.json',JSON.stringify({snapshot:{identity:{id:'previous-workspace-uuid',path:h.root}}}));assert.equal(new LocalVaultGateway({vaultPath:h.root,cachePath:path.join(h.root,'cache.json')}).identity.id,'previous-workspace-uuid');h.write('cache.json',JSON.stringify({snapshot:{identity:{id:'foreign-workspace-uuid',path:'/different'}}}));assert.equal(new LocalVaultGateway({vaultPath:h.root,cachePath:path.join(h.root,'cache.json')}).identity.id,'unpaired');});
test('capture preserves exact body and note; retry creates one immutable record',async t=>{const h=harness(t),input=request();const first=await h.gateway.capture(input),again=await h.gateway.capture(input);assert.equal(first.replayed,false);assert.equal(again.replayed,true);const raw=fs.readFileSync(path.join(h.root,first.note.path),'utf8');assert.equal(splitNote(raw).body,input.body);assert.equal(frontmatterOf(raw).caption,input.caption);assert.equal((await h.gateway.snapshot()).materials.length,1);await assert.rejects(h.gateway.capture({...input,sourceUrl:'https://example.test',body:'changed'}),{code:'OPERATION_REUSED'});assert.equal((await h.gateway.snapshot()).materials.length,1);});
test('attachment bytes, hashes and lazy native preview survive repeated save',async t=>{const h=harness(t),input=request({attachment});const result=await h.gateway.capture(input);await h.gateway.capture(input);const file=frontmatterOf(fs.readFileSync(path.join(h.root,result.note.path),'utf8')).original_file;const bytes=Buffer.from(attachment.dataUrl.split(',')[1],'base64');assert.deepEqual(fs.readFileSync(path.join(h.root,file)),bytes);assert.equal((await h.gateway.readAttachment(result.note.path)).dataUrl,attachment.dataUrl);assert.equal((await h.gateway.snapshot()).materials.length,1);});
test('existing note is never overwritten, including a preoccupied operation path',async t=>{const h=harness(t),input=request(),relative=`01_sources/cards/text/capture-${input.operationId}.md`;h.write(relative,'Existing user text');await assert.rejects(h.gateway.capture(input),{code:'CAPTURE_PATH_OCCUPIED'});assert.equal(fs.readFileSync(path.join(h.root,relative),'utf8'),'Existing user text');});
test('rejects symlink directories/files and path traversal for reads and writes',async t=>{const h=harness(t);h.write('outside.md','private');h.write('01_sources/cards/text/good.md','---\ntype: material\n---\nbody');fs.symlinkSync(path.join(h.root,'outside.md'),path.join(h.root,'01_sources/cards/text/link.md'));await assert.rejects(h.gateway.readNote('01_sources/cards/text/link.md'),{code:'PATH_FORBIDDEN'});await assert.rejects(h.gateway.readNote('../outside.md'),{code:'PATH_FORBIDDEN'});fs.symlinkSync(path.join(h.root,'01_sources/cards/text'),path.join(h.root,'01_sources/cards/web'));await assert.rejects(h.gateway.capture(request({sourceUrl:'https://example.test'})),{code:'PATH_FORBIDDEN'});});
test('source version conflict retains source and creates no target',async t=>{const h=harness(t);h.write('01_sources/cards/text/source.md','---\ntype: material\n---\nupdated');await assert.rejects(h.gateway.capture(request({sourcePath:'01_sources/cards/text/source.md',expectedSourceHash:hash('old')})),{code:'CONFLICT'});assert.equal((await h.gateway.snapshot()).materials.length,1);});
test('partial original save resumes same operation and blocks changed payload',async t=>{const h=harness(t),input=request({attachment}),original=h.gateway.exclusiveFile.bind(h.gateway);let fail=true;h.gateway.exclusiveFile=async(relative,bytes)=>{if(relative.endsWith('.md')&&fail){fail=false;throw Error('synthetic interrupted save');}return original(relative,bytes);};await assert.rejects(h.gateway.capture(input),/interrupted/);await assert.rejects(h.gateway.capture({...input,caption:'changed'}),{code:'OPERATION_REUSED'});const result=await h.gateway.capture(input);assert.equal(result.replayed,false);assert.equal((await h.gateway.snapshot()).materials.length,1);});
test('concurrent same operation returns one record and changed original is detected',async t=>{const h=harness(t),input=request({attachment});const [a,b]=await Promise.all([h.gateway.capture(input),h.gateway.capture(input)]);assert.equal(a.note.path,b.note.path);assert.equal(b.replayed,true);const relative=frontmatterOf(fs.readFileSync(path.join(h.root,a.note.path),'utf8')).original_file;fs.writeFileSync(path.join(h.root,relative),'changed');await assert.rejects(h.gateway.capture(input),{code:'ORIGINAL_CONFLICT'});});
test('AI policy still rejects instead of consuming calls',()=>{assert.throws(()=>rejectAiRequest(),{code:'AI_DISABLED'});});

test('existing JPEG extension remains readable without renaming original files',async t=>{const h=harness(t);h.write('01_sources/_originals/photo.jpeg',Buffer.from(attachment.dataUrl.split(',')[1],'base64'));assert.equal((await h.gateway.attachment('01_sources/_originals/photo.jpeg')).contentType,'image/jpeg');});
